stages:
  - build
  
buildJob:
  stage: build
  image: mcr.microsoft.com/dotnet/core/sdk:3.1
  
  script:
    - dotnet publish -f="netcoreapp3.1" -c Release -o Artifacts MelissaDataNameObjectWindowsNETExample/MelissaDataNameObjectWindowsNETExample.csproj

  artifacts:
    paths:
      - Artifacts/
    expire_in: 1 week
    
  tags:
    - docker-linux